version: '3.8'

services:
  master:
    build:
      context: ./master
    container_name: master
    ports:
      - '8000:8000'
    volumes:
      - ./master:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - simnet

  worker:
    build:
      context: ./worker
    environment:
      - ACCEL=2.5
      - TAU=1.0
      - STARTUP_DELAY=0.5
      - MASTER_URL=http://master:8000/report_result
    depends_on:
      - master
    networks:
      - simnet
    restart: 'no'

networks:
  simnet:
    driver: bridge
